config/routes.rb
Voter::Application.routes.draw do
  resources :users

  match 'signup', to: 'users#new'
  match 'signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'about', to: 'home#about'
  match 'contact', to: 'home#contact'
  match 'cast_votes', to: 'home#cast_votes'
  match 'create_votes', to: 'home#create_votes'
  match 'latest_votes', to: 'home#latest_votes'

  resources :sessions, only: [:new, :create, :destroy]

  resources :votes
  resources :options, only: [:new, :create, :destroy]
  root to: 'home#index'

  match 'cast_signal_vote', to: 'votes#cast_signal_vote'
  match 'cast_multi_vote', to: 'votes#cast_multi_vote'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :signed_in_user, only: [:index, :cast_votes, :create_votes, :latest_votes]
  def index
  	@create_votes = current_user.votes.limit(5)
  	@cast_votes = current_user.cast_votes.limit(5)
  	@last_votes = Vote.order("created_at DESC").limit(5)
  end
  def about
  end
  def contact
  end

  def cast_votes
    @cast_votes = current_user.cast_votes.paginate(per_page: 15,page: params[:page])
  end
  def create_votes
    @create_votes = current_user.votes.paginate(per_page: 15,page: params[:page])
  end
  def latest_votes
    @latest_votes = Vote.paginate(per_page: 15, page: params[:page], order: "created_at DESC")
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<script type="text/javascript">
$('.nav li').eq(<%= signed_in? ? '2' : '1' %>).attr('class', 'active');
</script>
<div class="row-fluid">
	<div class="span1"></div>
  <div class="clp_box span10" style="padding-top:20px;padding-bottom:20px;background-color:#ffffff;border-color:#ababab;" id="main_box">
		<legend>关于我们</legend>
		<p>
			<p><h4>我们是什么</h4></p>
			<p>爱投吧是一个集信息主被动收集，投票参与，投票发布，最新热点关注的免费的投票平台！</p>
		</p>
		<p>
			<p><h4>我们的理念</h4></p>
			<p>打造最人性化的投票平台！</p>
		</p>
		<p>
			<p><h4>一些介绍</h4></p>
			<p>	爱投吧在线投票系统适用于举办各类网上评选投票活动，前段框架由颇受欢迎的Bootstrap搭建，后台用Ruby语言编写。爱投吧用自己独特的人性化界面和人性化操作方式，吸引来访者参与投票，表示自己的真实情感。它适用于例如校园之星、政府机构的城市十大杰出青年、摄影机构的漂亮宝宝评选等人物评选活动，也适用于摄影作品，书法绘画作品的网上评选投票活动。
					我们要做的是打造一个全新的以投票评选为载体的人性化信息沟通平台，通过结合强大的数据采集、数据筛选、数据分析功能，一方面使得到的最终数据更全面、更真实、更权威，也就更有价值；另一方面又大幅降低得到这些数据所需付出的成本和时间。 
					爱投吧不仅是一个专业、强大的投票评选平台，也一直致力于打造一个免费的、公益性的公众调查平台。通过每天新增的问卷，使得每个人都有机会就自己感兴趣的问题发表自己的观点，也可以方便地开展在线调查、投票从而收集到大量的相关信息。
					爱投吧评选投票系统经过开发测试，终于展现在大家的眼前，我们希望，所有我们投入的都能给你带来哪怕一丁点的帮助，“使用户更好！”是我们所坚持的理念，用户的使用是对我们最大的肯定！
					尽管我们已经很努力测试修改了，但是，对于爱投吧来说，难免会有一些疏漏的地方，我们衷心地希望您能给我们相关的建议，以便爱投吧能更好地服务于您！
					如果您有什么相对我们说的，可以通过下面的方式联系我们！谢谢您的使用！</p>
		</p>
		<p>
			<p><h4>相关协议</h4></p>
			<p style="max-height:100px;overflow:hidden;overflow-y:scroll;">
				<p><strong>用户协议 欢迎加入</strong></p>
				<p><strong> 注册须知 </strong></p>
				<p>· 您必须是持有有效身份证明的合法公民才能注册成为本网站的用户。</p>
				<p>· 您只能注册一个本网站用户名。 </p>
				<p>您在注册成为本网站用户时，即表示您接受本协议所包含的所有条款和条件的约束。本协议阐述之条款和条件适用于您使用本网站所提供的各种工具和服务(下称“服务”)。 </p>

<p><strong>1. 接受条款。</strong></p> 
<p>进入本网站即表示您同意自己已经与本网站订立本协议，且您将受本协议的条款和条件 (“条款”) 约束。本网站可随时自行全权决定更改“条款”。如“条款”有任何变更，本网站将在其网站上刊载公告，通知予您。如您不同意相关变更，必须停止使用“服务”。经修订的“条款”一经在本网站公布后，立即自动生效。您应在第一次登录后仔细阅读修订后的“条款”，并有权选择停止继续使用“服务”；一旦您继续使用“服务”，则表示您已接受经修订的“条款”，当您与本网站发生争议时，应以最新的服务协议为准。除另行明确声明外，任何使“服务”范围扩大或功能增强的新内容均受本协议约束。 </p>

<p><strong>2. 谁可使用本网站？</strong> </p>
<p>“服务”仅供能够根据相关法律规定的有完全民事行为能力的人（自然人或公司）。本网站可随时自行全权决定拒绝向任何人士提供“服务”。</p>

<p><strong>3.1 注册义务。</strong></p> 
<p>如您在本网站注册，您同意：(a) 根据本网站所刊载的会员资料表格的要求，提供关于您或贵公司的真实、准确、完整和反映当前情况的资料；(b) 维持并及时更新会员资料，使其保持真实、准确、完整和反映当前情况。倘若您提供任何不真实、不准确、不完整或不能反映当前情况的资料，或本网站有合理理由怀疑该等资料不真实、不准确、不完整或不能反映当前情况，本网站有权暂停或终止您的注册身份及资料，并拒绝您在目前或将来对“服务”(或其任何部份) 以任何形式使用。如您代表一家公司或其他法律主体在本网站登记，则您声明和保证，您有权使该公司或其他法律主体接受本协议“条款”约束。 </p>

<p><strong>3.2 会员注册名、密码和保密。</strong> </p>
<p>在登记过程中，您将选择会员注册名和密码。您须自行负责对您的会员注册名和密码保密，且须对您在会员注册名和密码下发生的所有活动承担责任。您同意：(a) 如发现任何人未经授权使用您的会员注册名或密码，或发生违反保密规定的任何其他情况，您会立即通知本网站；及 (b) 确保您在每个上网时段结束时，以正确步骤离开网站。本网站不能也不会对因您未能遵守本款规定而发生的任何损失或损毁负责。 </p>

<p><strong>3.3 用户管理 </strong></p>
<p>用户单独承担发布内容的责任。用户对服务的使用是根据所有适用于服务的地方法律、国家法律和国际法律标准的。超出法律限定范围的一切事务由用户自己负责，与本站无关，用户须对自己在使用本网站服务过程中的行为承担法律责任。</p>

<p><strong>3.4 关于您的资料的规则。</strong> </p>
<p>用户保证所填写的资料真实且合法，对于一切违背国家法律的一切行动由用户自己负责，与本站无关。</p>
<p><strong>隐私声明</strong></p>
<p> 本网站以此声明对本站用户隐私保护的许诺。本网站的隐私声明正在不断改进中，随着本站服务范围的扩大，会随时更新隐私声明。我们欢迎您随时查看隐私声明。</p> 
<p><strong>使用说明</strong></p>
<p>本网站用户可以通过设定的密码来保护账户和资料安全。用户应当对其密码的保密负全部责任。请不要和他人分享此信息。如果您使用的是公共电脑，请在离开电脑时退出本网站以保证您的信息不被后来的使用者获取。 </p>

<p><strong>服务条款</strong></p>
<p>. 使用本网站的服务同时受本站用户协议的约束。</p>
<p>. 本站有权对以上条约进行更改，请用户对该条约多加关注。</p>
			</p>
		</p>
	</div>
	<div class="span1">
	</div>
	
</div>

app/views/home/cast_votes.html.erb
<div class="row-fluid">
	<div class="span1"></div>
	<% provide :title, "Index" %>
	<div class="clp_box span8" style="margin-top:5px;padding-top:20px;border-color:#ababab;background-color:#ffffff;" id="main_box">
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;我参与的
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @cast_votes %>
				</tbody>
			</table>
		</div>
		<%= will_paginate @cast_votes, {:previous_label => '上一页', :next_label => '下一页', class: 'flickr_pagination'} %>
	</div>
	<%= render 'shared/right_panel' %>
</div>

app/views/home/contact.html.erb
<script type="text/javascript">
	$('.nav li').eq(<%= signed_in? ? '3' : '2' %>).attr('class', 'active');
</script>
<div class="row-fluid">
	<div class="span2"></div>
  <div class="clp_box span8" style="padding-top:20px;padding-bottom:20px;background-color:#ffffff;border-color:#ababab;" id="main_box">
		<legend>联系我们</legend>
		<p>
			<p><h4>我们来自</h4></p>
			<p>电子科技大学通信学院</p>
		</p>
		<p>
			<p><h4>我们的联系方式</h4></p>
			<p>
				<strong>邮箱地址：</strong><small>clpliuping@126.com</small><br />
				<strong>联系电话：</strong><small>15196604105</small>
			</p>
		</p>
	</div>
	<div class="span2">
	</div>
</div>

app/views/home/create_votes.html.erb
<div class="row-fluid">
	<div class="span1"></div>
	<% provide :title, "Index" %>
	<div class="clp_box span8" style="margin-top:5px;padding-top:20px;border-color:#ababab;background-color:#ffffff;" id="main_box">
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;近期发布
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @create_votes %>
				</tbody>
			</table>
		</div>
		<%= will_paginate @create_votes, {:previous_label => '上一页', :next_label => '下一页', class: 'flickr_pagination'} %>
	</div>
	<%= render 'shared/right_panel' %>
</div>

app/views/home/index.html.erb
<script type="text/javascript">
	$('.nav li').eq(0).attr('class', 'active');
</script>
<div class="row-fluid">
	<div class="span1"></div>
	<% provide :title, "Index" %>
	<div class="clp_box span8" style="margin-top:5px;padding-top:20px;border-color:#ababab;background-color:#ffffff;" id="main_box">
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;我发布的
				<span class="pull-right">
					<%= link_to '更多...', create_votes_path, style: 'font-size:10px;color:#eeeeee;' %>
				</span>
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @create_votes %>
				</tbody>
			</table>
		</div>
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;我参与的
				<span class="pull-right">
					<%= link_to '更多...', cast_votes_path, style: 'font-size:10px;color:#eeeeee;' %>
				</span>
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @cast_votes %>
				</tbody>
			</table>
		</div>
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;近期发布
				<span class="pull-right">
					<%= link_to '更多...', latest_votes_path, style: 'font-size:10px;color:#eeeeee;' %>
				</span>
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @last_votes %>
				</tbody>
			</table>
		</div>
	</div>
	<%= render 'shared/right_panel' %>
</div>

app/views/home/latest_votes.html.erb
<div class="row-fluid">
	<div class="span1"></div>
	<% provide :title, "Index" %>
	<div class="clp_box span8" style="margin-top:5px;padding-top:20px;border-color:#ababab;background-color:#ffffff;" id="main_box">
		<div>
			<label class="label label-info" style="font-size:14px;padding:6px;">&nbsp;&nbsp;近期发布
			</label>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>序号</th>
						<th>主题</th>
						<th>截止时间</th>
						<th>参与人数</th>
					</tr>
				</thead>
				<tbody>
					<%= render partial: 'shared/vote_piece', collection: @latest_votes %>
				</tbody>
			</table>
		</div>
		<%= will_paginate @latest_votes, {:previous_label => '上一页', :next_label => '下一页', class: 'flickr_pagination'} %>
	</div>
	<%= render 'shared/right_panel' %>
</div>