config/routes.rb
Voter::Application.routes.draw do
  resources :users

  match 'signup', to: 'users#new'
  match 'signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'about', to: 'home#about'
  match 'contact', to: 'home#contact'
  match 'cast_votes', to: 'home#cast_votes'
  match 'create_votes', to: 'home#create_votes'
  match 'latest_votes', to: 'home#latest_votes'

  resources :sessions, only: [:new, :create, :destroy]

  resources :votes
  resources :options, only: [:new, :create, :destroy]
  root to: 'home#index'

  match 'cast_signal_vote', to: 'votes#cast_signal_vote'
  match 'cast_multi_vote', to: 'votes#cast_multi_vote'

end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  description :string(255)
#  multi       :boolean(1)
#  expiration  :datetime
#  minoptions  :integer(4)
#  maxoptions  :integer(4)
#  user_id     :integer(4)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Vote < ActiveRecord::Base
	attr_accessible :title, :description, :multi, :expiration, :options, :minoptions, :maxoptions, :caster_count
	validates :title, presence: true, length: { maximum: 15 }
	validates :description, length: { minimum: 6 }
	validates_presence_of :minoptions, :maxoptions

	has_many :user_voteships, dependent: :destroy
	has_many :cast_users, through: :user_voteships, source: :user, dependent: :destroy
	belongs_to :user
	has_many :options, dependent: :destroy

	attr_accessible :options_attributes
	accepts_nested_attributes_for :options, :reject_if => lambda { |a| a[:description].blank? }, allow_destroy: true
  # default_scope order: 'votes.created_at DESC'
  validate :must_be_not_expired
  validate :options_number

  def options_number
    errors.add(:base, "options_number limit errors") if minoptions <=0 || minoptions > maxoptions
  end
  def must_be_not_expired
    errors.add(:base, "Must be not expired") if expiration <= Time.now
  end
	def owner?(user)
		self.user_id == user.id
	end
end

app/controllers/votes_controller.rb
# coding: utf-8
class VotesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :show]
  before_filter :own_user,   only: [:edit, :destroy]
	def show
		@vote = Vote.find(params[:id])
	end
  def new
  	@vote = Vote.new
  	3.times { @vote.options.build }
  end
	def create
		@vote = current_user.votes.new(params[:vote])
    @vote = validates_vote(@vote)
    if @vote
      if @vote.save
        # flash[:success] = 'create a vote succeed'
        # redirect_to root_path
        respond_to do |format|
          format.js { render js: 'location.href="/"'}
        end
      else
        # render 'new'
        render_noty("发表失败，请重试。")
      end
    end
	end
	def edit
		@vote = Vote.find(params[:id])
	end
  def update
    @vote = Vote.find(params[:id])
    if @vote.update_attributes(params[:vote])
      # redirect_to @vote, notice: "Successfully updated vote."
      respond_to do |format|
        format.js { render js: 'location.href="/votes/' + "#{@vote.id}" + '"'}
      end
    else
      render_noty("更新失败，请修改。")
    end
  end
  def cast_signal_vote
    current_vote = Vote.find(params[:vote])
    if current_vote.expiration <= Time.now
      render_noty("投票已结束，谢谢关注。")
    else
      if params[:votes].nil?
        # flash[:errors] = 'can only one'
        render_noty("投票失败，请重试。")
      else
        if params[:votes].size == 1
          if current_user.cast_votes.include?(current_vote)
              render_noty("你已投过票了。")
          else
            current_user.user_voteships.create(vote_id: params[:vote]) unless current_user.cast_votes.include?(current_vote)
            option_ids = current_user.option_ids - current_vote.option_ids
            option_ids << params[:votes][:options]
            if current_user.attributes = {'option_ids' => option_ids}
              # flash[:success] = "cast succeed"
              @statistics = statistics(current_vote)
              respond_to do |format|
                format.js {render 'cast_vote', :formats => :js}
              end
            end
          end
        else
          # flash[:errors] = 'can only one'
          render_noty("投票失败，只能投一个，请重试。")
        end
      end
    end
    # redirect_to :back
  end
  def cast_multi_vote
    current_vote = Vote.find(params[:vote])
    if current_vote.expiration <= Time.now
      render_noty("投票已结束，谢谢关注。")
    else
      if current_user.cast_votes.include?(current_vote)
          render_noty("你已投过票了。")
      else
        if params[:votes].nil?
          # flash[:errors] = 'range min max'
          render_noty("投票失败，请重试。")
        else
          if params[:votes][:option_ids].size <= current_vote.maxoptions && params[:votes][:option_ids].size >= current_vote.minoptions
            current_user.user_voteships.create(vote_id: params[:vote]) unless current_user.cast_votes.include?(current_vote)
            option_ids = current_user.option_ids - current_vote.option_ids
            # if params[:votes].nil?
            #   if current_user.attributes = {'option_ids' => option_ids}
            #     flash[:success] = "cast succeed"
            #   end
            # else
            option_ids |= params[:votes][:option_ids]
            if current_user.attributes = {'option_ids' => option_ids}
              # flash[:success] = "cast succeed"
              @statistics = statistics(current_vote)
              respond_to do |format|
                format.js {render 'cast_vote', :formats => :js}
              end
            end
            # end
          else
            # flash[:errors] = 'range min max'
            render_noty('投票失败，该投票最少选' + "#{current_vote.minoptions}" + '项,最多选' + "#{current_vote.maxoptions}" + '项，请重试。')
          end
        end
      end
    end
    # redirect_to :back
  end

  private
  def own_user
    redirect_to :root unless Vote.find(params[:id]).owner?(current_user)
  end
  def statistics(vote)
    statistics = []
    total = UserOptionship.where("option_id in (?)", vote.option_ids).count
    vote.options.each do |option|
      option_total = UserOptionship.where("option_id = ?", option.id).count
      precent = option_total / total.to_f * 100
      statistics << [option_total.to_s + '票', precent]
    end
    statistics
  end
  def render_noty(noty)
    respond_to do |format|
      format.js { render :js => 'noty({"text":"' + "#{noty}" + '","theme":"noty_theme_twitter","layout":"topLeft","type":"success","animateOpen":{"height":"toggle"},"animateClose":{"height":"toggle"},"speed":500,"timeout":2500,"closeButton":true,"closeOnSelfClick":true,"closeOnSelfOver":false,"modal":false});' }
    end
  end

  def validates_vote(vote)
    validated_vote = false
    if vote.title.length <= 2
      render_noty("发表失败，主题太短了，请修改。")
    elsif vote.title.length > 15
      render_noty("发表失败，主题太长了，超过15字了，请修改。")
    elsif vote.description.length < 6
      render_noty("发表失败，描述太短了，为了别人能够理解你的意思，请修改。")
    elsif vote.expiration <= Time.now
      render_noty("发表失败，投票截止时间已经过期，请修改。")
    elsif vote.options.size < 2
      render_noty("发表失败，选项太少了，请添加,填写。")
    else
      if vote.multi
        minoptions = vote.minoptions = vote.minoptions.nil? ? 0 : vote.minoptions
        maxoptions = vote.maxoptions = vote.maxoptions.nil? ? 0 : vote.maxoptions
        if minoptions <= 0
          # flash[:errors] = 'minoptions can not be larger than maxoptions'
          # render 'new'
          render_noty("发表失败，最少项目不能为0，请修改。")
        elsif  minoptions > maxoptions
          render_noty("发表失败，最少项数目多余最多项数目，请修改。")
        elsif maxoptions > vote.options.size
          # flash[:errors] = 'maxoptions can not be larger than the number of vote\'s options'
          # render 'new'
          render_noty("发表失败，最多项数目多余有效选项数目" + "#{vote.options.size}" + "，请修改。")
        else
          validated_vote = vote
        end
      else
        vote.minoptions = 1
        vote.maxoptions = 1
        validated_vote = vote
      end
    end
    validated_vote
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<div class="clp_box span8" style="padding-top:20px;background-color:#ffffff;border-color:#ababab;" id="main_box">
	<%= form_for(@vote, remote: true) do |f| %>
		<div class="span12 row" style="margin-left:0;">
			<div class="span6">
				<span class="label label-info" style="font-size:16px;">主题</span>
				<small style="color:#bebebe;">(最多15个字)</small>
			</div>
			<div class="span12" style="margin-left:0;">
			<div class="clp_box span12"  onclick="show_after();" onmouseover="hover_style(this)" onmouseout="out_style(this)" style="cursor:pointer;margin:0px 0 20px 0;font-size:16px;letter-spacing:2px;text-align:center;font-family:'微软雅黑','Tahoma'; overflow:hidden;" id="input_before">
			<%= @vote.title.nil? ? '	' : @vote.title %>
			</div>
			<%= f.text_field :title, class: 'span12',
					onblur: 'show_before();',
					id: 'input_after',
					style: 'display:none;text-align:center;margin-bottom:20px;' %>
			</div>
		</div>
		<div class="span12 row" style="margin-left:0;">
			<div class="span6">
				<span class="label label-info" style="font-size:16px;">描述</span>
			</div>
			<div class="span12 well" style="margin-left:0;font-size:14px;color:#4c4c4c;">
				<%= f.text_area :description, :rows => 5, class: 'span12', style: 'width:100%;' %>
			</div>
		</div>
		<div class="span12" style="margin-left:0;">
			<div class="btn-group" data-toggle="buttons-radio">
				<a class="btn btn-info <%= 'active' if @vote.multi.nil? || !@vote.multi %>" id="singel_btn" onclick="setTimeout(function(){show_multi()},200)">单选</a>
				<a class="btn btn-info <%= 'active' unless @vote.multi.nil? || !@vote.multi %>" id="multi_btn" onclick="setTimeout(function(){show_multi()},200)">多选</a>
			</div>
			<%= f.hidden_field :multi, id: 'send_val', value: "#{@vote.multi.nil? ? 0 : @vote.multi}", style: 'display:none;' %><!-- 用于传送多选或单选值 -->
		</div>
		<div class="clp_box span12" style="margin-left:0;<%= 'display:none;' if @vote.multi.nil? || !@vote.multi %>" id="multi_box">
			<div class="demo">
				<p>
					<label for="amount"><strong>选择限制：</strong></label>
					<div>
						<span>最少：</span>
						<%= f.text_field :minoptions, value: "#{@vote.minoptions.nil? ? 1 : @vote.minoptions}",
								id: 'amount_min',
								style: 'max-width:15px;border:0;outline:none;font-weight:bold;cursor:default;width:43px;' %>
						<span>&nbsp;&nbsp;最多：</span>
						<%= f.text_field :maxoptions, value: "#{@vote.maxoptions.nil? ? 3 : @vote.maxoptions}",
								id: 'amount_max',
								style: 'max-width:15px;border:0;outline:none;font-weight:bold;cursor:default;width:43px;' %>
					</div>
				</p>
				<div id="slider-range"></div>
			</div>
		</div>
		<div class="span12" style="margin:0;margin-top:10px;">
			<label><strong style="color:#4b4b4b;">截止日期：</strong></label>
			<div class="row-fluid span12">
				<%= f.datetime_select :expiration, class: 'input-small', start_year: Time.now.year, default: Time.now %>
			</div>
		</div>
		<div class="span12" style="margin:0;"><hr style="border-top:1px dashed #ababab;" /></div>

		<div class="span12 row" style="margin-left:0;margin-top:0px;">
			<div class="clp_box span12" style="margin-left:0;margin-top:0px;" id="js_help_input">
				<div class="span12 well" style="margin-left:0;margin-top:10px;margin-bottom:10px;">
				  <%= f.fields_for :options do |builder| %>
				  	<%= render 'option_fields', f: builder %>
				  <% end %>
					<label><%= link_to_add_fields "+添加项", f, :options %></label>
				</div>
			</div>
		</div>
		<div class="span12" style="margin-left:0;"><hr style="border-top:1px dashed #ababab;" /></div>
		<div class="span12" style="margin-left:0;margin-bottom:20px;">
			<div class="span10" style="margin-left:0;text-align:right;">
				<%= link_to '返回首页', root_path, class: 'btn' %><span>&nbsp;&nbsp;</span>
				<%= f.submit "发布", class: 'btn btn-primary', disable_with: '发布中...' %>
			</div>
		</div>
	<% end %>
</div>

<%= stylesheet_link_tag 'source/css/jquery.ui.all' %>
<%= stylesheet_link_tag 'source/css/demos' %>
<style type="text/css">
	select{
		width:65px!important;
	}
</style>
<script type="text/javascript">
	function show_hot(){
		$('.carousel').carousel()
	}
	function show_error(){//显示选项错误
		var ele=$("#vote_error");
		ele.fadeIn();
	}
	function error_reload(){
		var ele=$("#vote_error");
		ele.hide();
	}
	function hover_style(ele){
		$(ele).css("border-color","#f89406");
	}
	function out_style(ele){
		$(ele).css("border-color","#e5e5e5");
	}
	function show_before(){
		var input_val=$("#input_after").val();
		$("#input_after").hide();
		$("#input_before").show();
		$("#input_before").html(input_val);
	}
	function show_after(){
		$("#input_before").hide();
		$("#input_after").show();
		$("#input_after").focus();
	}
	function show_multi(){
		var singel=$("#singel_btn").attr("class").indexOf("active");
		var multi=$("#multi_btn").attr("class").indexOf("active");
		var multi_box=$("#multi_box");
		var send_val=$("#send_val");
		if(singel==-1){
			multi_box.slideDown();
			send_val.attr('value', 1);
		}else{
			multi_box.slideUp();
			send_val.attr('value', 0);
		}
	}
	function range_fresh(ele){
		the_ele=$(ele).closest('div').filter(':visible').find('.clp_js_num');
		for(var i=0;i<the_ele.length;i++){
			the_ele.eq(i).html(String(eval(i+1)));
		}
	}
	function remove_item(ele,fresh){
		var key=$("#js_help_input input").length;
		if(key>1){
			var item=$(ele).closest("div");
			item.remove();
			range_fresh(fresh);
			slide_func();
		}
	}
	function add_item(ele,fresh){
		var the_ele=$(ele).closest("label");
		the_ele.before(
			'<div class="span12 form-inline" style="margin-left:0;margin-bottom:10px;">'+
						'<span class="clp_js_num label label-info">2</span>'+
						'<input type="text" class="input-xxlarge" style="margin-left:4px;" />'+
						'<span class="margin-left:2px;">&nbsp;&nbsp; </span>'+
						'<label><a href="javascript:;" onclick="remove_item(this,'+'\'.clp_js_num\''+');">&nbsp;删除此项</a></label>'+
					'</div>'
		);
		range_fresh(fresh);
		slide_func();
	}
</script>
<script>
		window.onload = slide_func;

  jQuery(function() {
    $('form').on('click', '.remove_fields', function(event) {
      $(this).closest('div').children('input[type=hidden]').val(true);
      $(this).closest('div').hide();
      range_fresh('.clp_js_num');
			slide_func();
      return event.preventDefault();
    });
    $('form').on('click', '.add_fields', function(event) {
      var regexp, time;
      time = new Date().getTime();
      regexp = new RegExp($(this).data('id'), 'g');
      $(this).closest('label').before($(this).data('fields').replace(regexp, time));
      range_fresh('.clp_js_num');
			slide_func();
      return event.preventDefault();
    });
    slide_func();
		range_fresh('.clp_js_num');
  });
	function slide_func(){$(function() {
		var the_max=$("#js_help_input input").filter(':visible').length;
		var ele1=parseInt($("#amount_min").val());
		var ele2=parseInt($("#amount_max").val());
		$( "#slider-range" ).slider({
			range: true,
			min: 1,
			max: the_max,
			values: [ ele1, ele2 ],
			slide: function( event, ui ) {
				$( "#amount_min" ).val( ui.values[ 0 ] );
				$( "#amount_max" ).val( ui.values[ 1 ] );
			}
		});
		$( "#amount_min" ).val( $( "#slider-range" ).slider( "values", 0 ) );
		$( "#amount_max" ).val( $( "#slider-range" ).slider( "values", 1 ) );
	});
	}
</script>

app/views/votes/_multi_vote.html.erb
<div class="span12" style="margin-left:0;">
		<span style="margin-left:5px;">最少 <span class="badge" id="limit_items_min"><%= @vote.minoptions %></span> 项 -</span>
	<span style="margin-left:5px;">最多 <span class="badge badge-important" id="limit_items"><%= @vote.maxoptions %></span> 项</span>
</div>
<div class="span12 row" style="margin-left:0;">
	<div class="span12">
		<div class="form-inline span12" style="margin-left:0;">
			<div class="clp_aligncenter span6">
				<strong>选项</strong>
			</div>
			<div class="clp_aligncenter span1"><strong>票数</strong></div>
			<div class="span1"></div>
			<div class="clp_aligncenter span4"><strong>百分比</strong></div>
		</div>
	<%= form_tag('/cast_multi_vote', remote: true) do %>
		<%= hidden_field_tag 'vote', @vote.id %>
		<% options.each_with_index do |option, index| %>

		<div class="form-inline span12" style="margin-left:0;">
			<div class="span6">
				<label><span><%= index + 1 %></span>. &nbsp;&nbsp;</label>
				<label class="checkbox" onclick="check_choose();">
					<% if current_user.cast_votes.include?(@vote) || @vote.expiration <= Time.now %>
						<%= check_box_tag "#{option.id}", "#{option.id}",
								current_user.options.include?(option),
								name: 'votes[option_ids][]',
								disabled: 'disabled' %>
					<% else %>
						<%= check_box_tag "#{option.id}", "#{option.id}",
									current_user.options.include?(option),
									name: 'votes[option_ids][]' %>
					<% end %>
				  <span>&nbsp;</span>
					<%= label_tag "#{option.id}",
								truncate(option.description, length: 20, omission: '...'),
								rel: 'tooltip',
								title: option.description,
								onmouseover: '$(this).tooltip("show")',
								style: 'color:#3b3b3b;' %>
				</label>
			</div>
			<% if current_user.cast_votes.include?(@vote) || @vote.expiration <= Time.now %>
				<div class="span1">
					<span class="badge badge-success">
						<%= option_total = UserOptionship.where("option_id = ?", option.id).count %>票
					</span>
				</div>
				<div class="span1"></div>
						<% total = UserOptionship.where("option_id in (?)", @vote.option_ids).count %>
				
				<div class="span4">
					<div class="progress progress-striped">
						<div class="bar"
							style="width: <%= number_to_percentage(option_total/total.to_f*100, precision: 2) %>;"
							rel="tooltip"
							title="<%= number_to_percentage(option_total/total.to_f*100, precision: 2) %>"
							onmouseover="$(this).tooltip('show')" >
						</div>
					</div>
				</div>
			<% else %>
				<div class="span1">
					<span class="badge badge-success">*票</span>
				</div>
				<div class="span1"></div>
				<div class="span4">
					<div class="progress progress-striped">
						<div class="bar" style="width: 0%;" rel="tooltip" title="请先投票" onmouseover="$(this).tooltip('show')" ></div>
					</div>
				</div>
			<% end %>

		</div>
		<% end %>

		<div class="span12" style="margin-left:0;">
			<hr style="border-top:1px dashed #ababab" />
		</div>
		<div class="span12" style="margin-left:0;margin-bottom:10px;">
			<% if @vote.expiration <= Time.now %>
				<button class="btn btn-primary pull-right" style="margin-right:10px;" disabled="disabled">投票已结束</button>
			<% else %>
				<%= submit_tag '投  票',
						disable_with: '投票中...',
						class: 'btn btn-primary pull-right',
						style: 'margin-right:10px;',
						onclick: 'error_reload();',
						id: 'ok_button',
						disabled: 'disabled' %>
			<% end %>
			<%= link_to '修改', edit_vote_path(@vote), class: 'btn' if @vote.owner?(current_user) %>
		</div>

		
	<% end %>
		
		<div class="span12 alert alert-error" style="margin-left:0;margin-top:10px;display:none;" id="vote_error">
			<strong>错误！</strong>选项有限制哦！下次别忘了啦！
		</div>
	</div>
</div>

app/views/votes/_option_fields.html.erb
<div class="span12 form-inline" style="margin-left:0;margin-bottom:10px;">
	<span class="clp_js_num label label-info">1</span>
	<%= f.text_field :description, class: 'input-xxlarge' %>
	<%= f.hidden_field :_destroy %>
	<span>&nbsp;&nbsp;</span>
	<label>
		<%= link_to "删除此项", 'javascript:;',
				class: 'remove_fields'
				 %>
	</label>
</div>

app/views/votes/_signal_vote.html.erb
<div class="span12" style="margin-left:0;">
	<span style="margin-left:5px;">只能选 <span class="badge badge-important" id="limit_items">1</span> 项</span>
</div>
<div class="span12 row" style="margin-left:0;">
	<div class="span12">
		<div class="form-inline span12" style="margin-left:0;">
			<div class="clp_aligncenter span6">
				<strong>选项</strong>
			</div>
			<div class="clp_aligncenter span1"><strong>票数</strong></div>
			<div class="span1"></div>
			<div class="clp_aligncenter span4"><strong>百分比</strong></div>
		</div>
	<%= form_tag('/cast_signal_vote', remote: true) do %>
		<%= hidden_field_tag 'vote', @vote.id %>
		<% options.each_with_index do |option, index| %>

		<div class="form-inline span12" style="margin-left:0;">
			<div class="span6">
				<label><span><%= index + 1 %></span>. &nbsp;&nbsp;</label>
				<label class="checkbox">
					<% if current_user.cast_votes.include?(@vote) || @vote.expiration <= Time.now %>
						<%= radio_button 'votes', 'options', option.id, checked: current_user.options.include?(option), disabled: 'disabled' %><span>&nbsp;</span>
					<% else %>
						<%= radio_button 'votes', 'options', option.id, checked: current_user.options.include?(option) %><span>&nbsp;</span>
					<% end %>
					<%= label_tag 'votes_options_' + "#{option.id}",
								truncate(option.description, length: 20, omission: '...'),
								rel: 'tooltip',
								title: option.description,
								onmouseover: '$(this).tooltip("show")',
								style: 'color:#3b3b3b;' %>
				</label>
			</div>
			<% if current_user.cast_votes.include?(@vote) || @vote.expiration <= Time.now %>
				<div class="span1">
					<span class="badge badge-success">
						<%= option_total = UserOptionship.where("option_id = ?", option.id).count %>票
					</span>
				</div>
				<div class="span1"></div>
						<% total = UserOptionship.where("option_id in (?)", @vote.option_ids).count %>
				
				<div class="span4">
					<div class="progress progress-striped">
						<div class="bar"
							style="width: <%= number_to_percentage(option_total/total.to_f*100, precision: 2) %>;"
							rel="tooltip"
							title="<%= number_to_percentage(option_total/total.to_f*100, precision: 2) %>"
							onmouseover="$(this).tooltip('show')" >
						</div>
					</div>
				</div>
			<% else %>
				<div class="span1">
					<span class="badge badge-success">*票</span>
				</div>
				<div class="span1"></div>
				<div class="span4">
					<div class="progress progress-striped">
						<div class="bar" style="width: 0%;" rel="tooltip" title="请先投票" onmouseover="$(this).tooltip('show')" ></div>
					</div>
				</div>
			<% end %>
		</div>
		<% end %>
		<div class="span12" style="margin-left:0;">
			<hr style="border-top:1px dashed #ababab" />
		</div>
		<div class="span12" style="margin-left:0;margin-bottom:10px;">
			<% if @vote.expiration <= Time.now %>
				<button class="btn btn-primary pull-right" style="margin-right:10px;" disabled="disabled">投票已结束</button>
			<% else %>
				<%= submit_tag '投  票',
						disable_with: '投票中...',
						class: 'btn btn-primary pull-right',
						style: 'margin-right:10px;',
						onclick: 'error_reload();' %>
			<% end %>
			<%= link_to '修改', edit_vote_path(@vote), class: 'btn' if @vote.owner?(current_user) %>
		</div>		
	<% end %>
		<div class="span12 alert alert-error" style="margin-left:0;margin-top:10px;display:none;" id="vote_error">
			<strong>错误！</strong>选项有限制哦！下次别忘了啦！
		</div>
	</div>
</div>

app/views/votes/cast_vote.js.erb
noty({"text":"投票成功，谢谢参与。","theme":"noty_theme_twitter","layout":"topLeft","type":"success","animateOpen":{"height":"toggle"},"animateClose":{"height":"toggle"},"speed":500,"timeout":2500,"closeButton":true,"closeOnSelfClick":true,"closeOnSelfOver":false,"modal":false});

badges = $('.span1').children('.badge');
bars = $('.bar');
$('#cast_counter1').html(parseInt($('#cast_counter1').html()) + 1);
$('#cast_counter2').html(parseInt($('#cast_counter2').html()) + 1);
<% @statistics.each_with_index do |s, i| %>
	badges.eq(<%= i %>).html("<%= s[0] %>");
	bars.eq(<%= i %>).attr('style', 'width: <%= s[1].round(2) %>%');
	bars.eq(<%= i %>).attr('title', '<%= s[1].round(2) %>%');
	bars.eq(<%= i %>).attr('data-original-title', '<%= s[1].round(2) %>%');
<% end %>

app/views/votes/edit.html.erb
<% provide(:title, 'Edit Vote') %>

<div class="row-fluid">
	<div class="span1"></div>
	<%= render 'form' %>
	<%= render 'shared/right_panel' %>
</div>

app/views/votes/new.html.erb
<script type="text/javascript">
	$('.nav li').eq(1).attr('class', 'active');
</script>
<% provide(:title, 'New Vote') %>

<div class="row-fluid">
	<div class="span1"></div>
	<%= render 'form' %>
	<%= render 'shared/right_panel' %>
</div>

app/views/votes/show.html.erb
<% provide :title, @vote.title %>
<div class="row-fluid">
	<div class="span1"></div>
	<div class="clp_box span8" style="padding-top:20px;background-color:#ffffff;border-color:#ababab;" id="main_box">
		<div class="span12 row">
			<div class="span12">
				<span class="label label-info" style="font-size:16px;">主题</span>
				<span class="pull-right" style="margin-right:5px;">参与人数:<span class="badge badge-important" id="cast_counter1"><%= @vote.cast_users.count %></span></span>
			</div>
			<div class="clp_box span12" style="margin:0px 0 20px 0;font-size:16px;letter-spacing:2px;text-align:center;font-family:'微软雅黑','Tahoma';overflow:hidden;">
				<strong><%= @vote.title %></strong>
			</div>
		</div>
		<div class="span12 row" style="margin-left:0;">
			<div class="span6">
				<span class="label label-info" style="font-size:16px;">描述</span>
			</div>
			<div class="span12 well" style="margin-left:0;font-size:14px;color:#4c4c4c;overflow:hidden;">
				<%= @vote.description %>
			</div>
		</div>
		<div class="span12" style="margin-left:0;">
			<div class="span6">
				<span class="label label-info" style="font-size:16px;">时间</span>
			</div>
			<div class="clp_box span12" style="margin:0px 0 20px 0;font-size:14px;letter-spacing:2px;text-align:center;font-family:'微软雅黑','Tahoma';">
				<strong><%= @vote.created_at.strftime("%Y年%m月%d日 %H:%M") %>——<%= @vote.expiration.strftime("%Y年%m月%d日 %H:%M") %></strong>
			</div>
		</div>
		<div class="span12" style="margin-left:0;"><hr style="border-top:1px dashed #ababab" /></div>

		<% if @vote.multi %>
			<%= render 'multi_vote', options: @vote.options %>
		<% else %>
			<%= render 'signal_vote', options: @vote.options %>
		<% end %>

	</div>
	<%= render 'shared/right_panel' %>
</div>
<script type="text/javascript">
	function show_hot(){
		$('.carousel').carousel()
	}
	function show_error(){//显示选项错误
		var ele=$("#vote_error");
		ele.fadeIn();
	}
	function error_reload(){
		var ele=$("#vote_error");
		ele.hide();
	}
	function check_choose(){
		var num=parseInt($("#limit_items").html());
		var num_min=parseInt($("#limit_items_min").html());
		var choice=$(".checkbox input");
		var temp=0;
		disable_btn("#ok_button");
		for(var i in choice){
			if(choice.eq(i).attr("checked")){
				temp++;
				if(temp>num||temp<num_min){
					disable_btn("#ok_button");
				}else{
					enable_btn("#ok_button");
				}
			}
			
		}
	}
</script>