config/routes.rb
Voter::Application.routes.draw do
  resources :users

  match 'signup', to: 'users#new'
  match 'signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'about', to: 'home#about'
  match 'contact', to: 'home#contact'
  match 'cast_votes', to: 'home#cast_votes'
  match 'create_votes', to: 'home#create_votes'
  match 'latest_votes', to: 'home#latest_votes'

  resources :sessions, only: [:new, :create, :destroy]

  resources :votes
  resources :options, only: [:new, :create, :destroy]
  root to: 'home#index'

  match 'cast_signal_vote', to: 'votes#cast_signal_vote'
  match 'cast_multi_vote', to: 'votes#cast_multi_vote'

end

app/views/layouts/_footer.html.erb
<footer class="footer"  id="js_hide_1">
	<p>
		<span class="pull-right" style="text-align: center;">ATB All Rights Reserved</span>
		<small>
			ATB投票系统  专注投票<br />
			本投票系统是一个需注册性质的投票平台，在这个平台上你可以找到很多对你有用的东西<br />
			你可以再这个平台上收集你感兴趣的统计资料，当然，事先要进行注册<br />
			你还可以通过查看最新的投票主题，以此判断近期的社会话题
		</small>
	</p>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top" id="js_slideup">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'ATB投票系统', root_path, class: 'brand' %>
      <% if signed_in? %>
        <div class="btn-group pull-right">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i><%= current_user.name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to '个人资料', edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to '退出', signout_path, method: :delete %></li>
          </ul>
        </div>
      <% end -%>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to '首页', root_path %></li>
          <% if signed_in? %>
            <li><%= link_to '发起投票', new_vote_path %></li>
          <% end -%>
          <li><%= link_to '关于我们', about_path %></li>
          <li><%= link_to '联系我们', contact_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Le styles -->
  <%= stylesheet_link_tag 'source/css/bootstrap' %>
  <style>
    body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			background-image:url('<%= image_path "source/images/masked.png" %>');
			background-postion:0 20px;
			background-repeat:repeat-x;
    }
  </style>
  <%= stylesheet_link_tag 'source/css/bootstrap-responsive' %>
  <%= stylesheet_link_tag 'source/css/clp-base' %>
  <%= stylesheet_link_tag 'pagination' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Le fav and touch icons -->		
	<link rel="shortcut icon" href="<%= image_path "source/ico/favicon.ico" %>">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= image_path "source/ico/apple-touch-icon-144-precomposed.png" %>">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= image_path "source/ico/apple-touch-icon-114-precomposed.png" %>">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= image_path "source/ico/apple-touch-icon-72-precomposed.png" %>">
	<link rel="apple-touch-icon-precomposed" href="<%= image_path "source/ico/apple-touch-icon-57-precomposed.png" %>">

  <%= javascript_include_tag "source/js/bootstrap-transition" %>
  <%= javascript_include_tag "source/js/bootstrap-alert" %>
  <%= javascript_include_tag "source/js/bootstrap-modal" %>
  <%= javascript_include_tag "source/js/bootstrap-dropdown" %>
  <%= javascript_include_tag "source/js/bootstrap-scrollspy" %>
  <%= javascript_include_tag "source/js/bootstrap-tab" %>
  <%= javascript_include_tag "source/js/bootstrap-tooltip" %>
  <%= javascript_include_tag "source/js/bootstrap-popover" %>
  <%= javascript_include_tag "source/js/bootstrap-button" %>
  <%= javascript_include_tag "source/js/bootstrap-collapse" %>
  <%= javascript_include_tag "source/js/bootstrap-carousel" %>
  <%= javascript_include_tag "source/js/bootstrap-typeahead" %>
  <%= javascript_include_tag "source/js/jquery.ui.core" %>
  <%= javascript_include_tag "source/js/jquery.ui.widget" %>
  <%= javascript_include_tag "source/js/jquery.ui.mouse" %>
  <%= javascript_include_tag "source/js/jquery.ui.slider" %>
  <%= javascript_include_tag "source/js/clp_base" %>

	<script type="text/javascript">
		function alert_error(){
			$("#error_tips").fadeIn();
		}
		function show_hot(){
			$('.carousel').carousel()
		}
	</script>
  <%= javascript_include_tag "votes" %>

</head>
<body onload="show_hot();">
	<%= render 'layouts/navbar' %>
  <div class="container-fluid">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
<% debug(params) if Rails.env.development? %>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>

    <!-- Le styles -->
    <%= stylesheet_link_tag 'source/css/bootstrap' %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
				background-image:url('<%= image_path "source/images/masked.png" %>');
				background-postion:0 20px;
				background-repeat:repeat-x;
      }
    </style>
    <%= stylesheet_link_tag 'source/css/bootstrap-responsive' %>
    <%= stylesheet_link_tag 'source/css/clp-base' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->		
		<link rel="shortcut icon" href="<%= image_path "source/ico/favicon.ico" %>">
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= image_path "source/ico/apple-touch-icon-144-precomposed.ico" %>">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= image_path "source/ico/apple-touch-icon-114-precomposed.ico" %>">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= image_path "source/ico/apple-touch-icon-72-precomposed.ico" %>">
		<link rel="apple-touch-icon-precomposed" href="<%= image_path "source/ico/apple-touch-icon-57-precomposed.ico" %>">

	  <%= javascript_include_tag "source/js/bootstrap-transition" %>
	  <%= javascript_include_tag "source/js/bootstrap-alert" %>
	  <%= javascript_include_tag "source/js/bootstrap-button" %>
    <%= javascript_include_tag "source/js/bootstrap-typeahead" %>
	  <%= javascript_include_tag "source/js/clp_base" %>
    <script type="text/javascript">
      function alert_error(){
        $("#error_tips").fadeIn();
      }
      function check_input(){
        $("#error_tips").hide();
        var ele1=$("#input01").val();
        var ele2=$("#input02").val();
        if(ele1&&ele2){}
        else{alert_error();}
      }
      function error_cancel(){
        $("#error_tips").hide();
      }
      function sign_action(){
        var ele1=$("#js_hide_1");
        var ele2=$("#js_hide_2");
        var ele3=$("#js_hide_3");
        var eletop=$("#js_top");
        var ele=$("#main_box");
        var eleup=$("#js_slideup");
        ele1.stop().fadeOut("fast").queue(function(){
          ele2.stop().fadeOut("fast").queue(function(){
            ele3.stop().fadeOut("fast").queue(function(){
              eletop.stop().animate({"margin-top":"0px"},200).queue(function(){
                eleup.stop().slideUp("normal").queue(function(next){
                  ele.stop().fadeIn("fast").animate({"margin-top":"10px"},200);
                  next();
                })
                
              })
            })
          })
        })
      }
      function sign_action_back(){
        var ele1=$("#js_hide_1");
        var ele2=$("#js_hide_2");
        var ele3=$("#js_hide_3");
        var eletop=$("#js_top");
        var ele=$("#main_box");
        var eleup=$("#js_slideup");
          ele.fadeOut().queue(function(){eleup.fadeIn().queue(function(){
            eletop.stop().animate({"margin-top":"150px"},200).queue(function(){
              ele3.stop().fadeIn().queue(function(){
                ele2.stop().fadeIn().queue(function(){
                  ele1.stop().fadeIn().queue(function(){
                    stop();
                  })
                })
              })
            })
          })
          
          })  
      }
      function check_all_input_ok(){
        var key=check_input_ok('#2_input_group','#3_input_group','6','20','#ok_btn','off');
        var username=$("#1_input_group").val();
        var min=4;
        var max=8;
        if(username.length>=min&&username.length<=max&&key){
          enable_btn("#ok_btn");
        }else{
          disable_btn("#ok_btn");
        }
        
      }
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span1"></div>
        <%= yield %>
        <%= render 'shared/right_panel' %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
  <%= debug(params) if Rails.env.development? %>
</html>